spring:
  datasource:
    # url: jdbc:mysql://localhost:3306/test_spring?useUnicode=true&characterEncoding=UTF-8
    url: jdbc:mysql://[address:port]/[database_name]?[options]
    username: root
    password: 1234567890

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: [.entity]

server:
  port: 8999
