spring:
  redis:
    database: 0
#    password:
    port: 6379
#    host: 192.168.66.128
    host: 127.0.0.1
    lettuce:
      pool:
        min-idle: 5
        max-idle: 10
        max-active: 8
        max-wait: 1ms
      shutdown-timeout: 100ms




server:
  port: 8999